roles:
  - name: robertdebock.bootstrap
    version: 7.1.7
  - name: robertdebock.users
    version: 6.1.8
  - name: oefenweb.ufw
    src: https://github.com/Oefenweb/ansible-ufw.git
    scm: git
    version: v4.1.16

collections:
  - name: community.general
  - name: devsec.hardening
    version: 10.5.2
