docker_engine_manage_repository: true
docker_engine_package_state: present
docker_engine_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
docker_engine_service_enabled: true
docker_engine_service_state: started
docker_engine_users: []
docker_engine_apt_repository_url: https://download.docker.com/linux/debian
docker_engine_apt_keyring_path: /etc/apt/keyrings/docker.asc
